name: WeekSpark deployment workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        REACT_APP_GOOGLE_MAPS_API_KEY: ${{ env.REACT_APP_GOOGLE_MAPS_API_KEY }}
        REACT_APP_CLOUD_NAME: ${{ env.REACT_APP_CLOUD_NAME }}
        REACT_APP_PRESET: ${{ env.REACT_APP_PRESET }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm i
    - run: npm run build --if-present
    - run: echo "Hello $REACT_APP_PRESET"
    - run: echo "from secrets ${{env.REACT_APP_PRESET}}"
  
  build_backend:
       needs: build_frontend
       runs-on: self-hosted
       defaults:
        run:
          working-directory: flask-server
       strategy:
         fail-fast: false
         matrix:
            python-version: ["3.10"]
       steps:
        - name: Initialize Python 3.10
          env:
            SECRET_KEY: ${{ env.SECRET_KEY }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
