name: WeekSpark deployment workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm i
    - run: npm run build --if-present
  
  build_backend:
       runs-on: self-hosted
       defaults:
        run:
          working-directory: flask-server
       strategy:
         fail-fast: false
         matrix:
            python-version: ["3.10"]
       steps:
        - name: Initialize Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r flask-server/requirements.txt
